### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by brutto01** [cityofasheville/SA1_SkillsTask#1]
Hi Scott,

Hope you're having a productive week.  I have a few questions about the assignment. 

For this exercise, do you only want analysis only on accrual types 4, 5, and 6, which are related to comp time?

Would you like to include only the records in the EmployeeMaster file with a value of "A" in the e_status column, or would you like to include "I" as well?

How is accrual type "Comp XMP" calculated?

Which field, if any, indicates whether an employee is exempt, or nonexempt?  

There are three columns in the AccrualBalances file related to the accrual balances, 

ac_earned_to_date

ac_used_to_date

ac_quant_avail

which of these three field do you want used as the "current accumulated comp time available to the employee" (by accrual type)?  I see some possible discrepancies, but it may just be the way hours for accrual type COMP XMP and 1.5 are calculated.  For example: 

employee 1004, accrual type COMP XMP(4), has earned to date, 3.5, used to date, 83.37, and quantify available, -13.87.

employee 5750, accrual type 1.5(5), has earned to date, 22.66, used to date, 13.88, and quantity available, 77.595.

Accrual type 1.0(6) does not have any obvious discrepancies, earned to date minus used to date equal the quantity available. 

Please let me know what I need to clarify about my questions. 

Thank you, 
Frank

**Comment by sbarnwell** [comment]
For this exercise, do you only want analysis only on accrual types 4, 5, and 6, which are related to comp time?
***Yes, that would be fine.

Would you like to include only the records in the EmployeeMaster file with a value of "A" in the e_status column, or would you like to include "I" as well?
***A = Active and I =  Inactive, so yes, analyzing the “A” records makes sense.

How is accrual type "Comp XMP" calculated?
***“Comp XMP” refers to comp hours earned by salaried, “exempt” employees. Each hour above the scheduled work week is credited as an hour in “Comp XMP” for these employees

Which field, if any, indicates whether an employee is exempt, or nonexempt?
***“Exempt” employees will have comp time in the “Comp XMP” category. Non-exempt employees have comp time in the “Comp 1.5” category meaning that it is earned at a time and a half rate. “Comp 1.0” is no longer earned and there are no balances remaining in this category.

There are three columns in the AccrualBalances file related to the accrual balances,
ac_earned_to_date
ac_used_to_date
ac_quant_avail
which of these three field do you want used as the "current accumulated comp time available to the employee" (by accrual type)? 
***“ac_quant_avail” represents the time available by leave category and can include hours carried over from the previous year.

I see some possible discrepancies, but it may just be the way hours for accrual type COMP XMP and 1.5 are calculated. 
_**“ac_earned_to_date” represents hours earned this year (not including hours carried over)
*_*“ac_used_to_date” represents hours used this year
