### ISSUE TITLE
Two Quick Questions

### ISSUE THREAD

**Issue by brutto01** [cityofasheville/SA1_SkillsTask#2]
Hi Scott, 

TGIF!  

There are 9 records in the accrual balances file with field [ac_active_y_n] equal to 'N'.  I don't want to make any assumptions.  How do you use this field?

How does an employee use their comp time?  Does he, or she take vacation time, get a check for the amount of comp time, or a combination of both. 

Thank you, 
Frank

**Comment by sbarnwell** [comment]
Hey Frank,
The [ac_active_y_n] tells whether or not an accrual record is active or inactive. In principle, all accrual records for inactive employees should be "N". However, an active employee could have a "N" accrual value if they changed position from non exempt to exempt. In that case, the non exempt accrual records would be inactive but that employee would have active accrual records as exempt.

Employees use comp time for time off prior to using vacation or sick hours. In other words, the comp accrual should be zero before vacation or sick hours are used.

I hope this helps.

Thanks,
Scott
